"""
Response caching (Op-6) — unit-economics defense.

Two layers, both keyed on the monotonic ``kg_version`` so an ingestion
refresh transparently invalidates everything:

- tool-result cache: (tool_name, normalized_params, kg_version)
- agent-response cache: (normalized_query, agent_version, kg_version)

Every operation is fail-safe: any cache error degrades to a normal
(uncached) call. Cache reads are free to the user — callers must skip
quota accounting on a hit. No PII enters cache keys (params/queries are
normalised, never user identifiers).
"""

# NOTE: generated by scripts/sync_pip_package.py from the hosted
# mosaic/src/mcp/cache.py — do NOT edit here. Edit the hosted file and re-run the sync,
# or the published package silently ships stale KG logic.

from __future__ import annotations

import hashlib
import json
import logging
import os
import time
from typing import Any

from mosaic_mcp.db.connection import get_pool

logger = logging.getLogger(__name__)

# Tools that mutate state, and per-user reads — never cached.
NON_CACHEABLE: frozenset[str] = frozenset({
    # Writes — caching a mutation is meaningless.
    "mosaic_watchlist_create",
    "mosaic_watchlist_add_item",
    "mosaic_target_wishlist_add",
    # Per-user reads. These MUST stay here: the cache key is
    # (tool_name, normalized_params, kg_version) plus the injected `__tier`,
    # and carries **no principal**. Two users asking for the same
    # watchlist_id at the same tier therefore produce the same key, so a
    # cache hit would hand user B the response computed for user A —
    # bypassing the ownership check in get_watchlist()/list_watchlists()
    # entirely, since a hit returns before the query ever runs.
    #
    # Found the hard way: after ownership scoping landed, the ownership
    # tests failed because a stale entry from a prior run was served without
    # calling the query layer at all. The fix was incomplete without this.
    #
    # Caching them is also wrong on freshness grounds — add an item, read it
    # back, and you would see the pre-add list for up to an hour.
    "mosaic_watchlist_get",
    "mosaic_watchlist_list",
})

# Per-tool TTL seconds; _DEFAULT_TTL for anything unlisted.
_DEFAULT_TTL = 3600
_TTL_BY_TOOL: dict[str, int] = {
    "mosaic_get_target_profile": 86_400,
    "mosaic_kg_stats": 3_600,
    "mosaic_find_opportunities": 21_600,
    "mosaic_find_undruggable_targets": 21_600,
}
_AGENT_TTL = 86_400

_kg_cache: dict[str, Any] = {"at": 0.0, "v": None}


def _db():
    return get_pool()


def _kg_version() -> int:
    """Current kg_version, cached in-process for 60s."""
    now = time.time()
    if _kg_cache["v"] is not None and now - _kg_cache["at"] < 60:
        return _kg_cache["v"]
    v = 1
    try:
        rows = _db().execute("SELECT kg_version FROM kg_metadata WHERE id = 1")
        if rows and rows[0].get("kg_version") is not None:
            v = int(rows[0]["kg_version"])
    except Exception as e:
        logger.debug("kg_version read failed, using %s: %s", v, e)
    _kg_cache.update(at=now, v=v)
    return v


def normalize_params(params: dict[str, Any]) -> str:
    """Stable, PII-free canonical form of tool params.

    Lowercases string scalars (entity names are case-insensitive here),
    sorts keys, drops None, and serialises deterministically.
    """
    def norm(v: Any) -> Any:
        if isinstance(v, str):
            return v.strip().lower()
        if isinstance(v, dict):
            return {k: norm(v[k]) for k in sorted(v) if v[k] is not None}
        if isinstance(v, (list, tuple)):
            return [norm(x) for x in v]
        return v

    clean = {k: norm(params[k]) for k in sorted(params) if params[k] is not None}
    return json.dumps(clean, separators=(",", ":"), default=str)


def _key(*parts: Any) -> str:
    return hashlib.sha256("|".join(str(p) for p in parts).encode()).hexdigest()


def _get(table: str, key: str) -> Any | None:
    try:
        rows = _db().execute(
            f"SELECT response FROM {table} "  # noqa: S608 - table is a literal
            "WHERE cache_key = %s AND expires_at > NOW()",
            (key,),
        )
        if rows:
            return rows[0]["response"]
    except Exception as e:
        logger.debug("cache get skipped (%s): %s", table, e)
    return None


# --- tool-result cache ----------------------------------------------------

def _bypass() -> bool:
    """Is the cache switched off for this process?

    ⚠️ THE 44-TOOL SWEEP CANNOT WORK WITHOUT THIS, and finding out why is
    instructive. The cache keys on `kg_version`, NOT on code version, so a
    formatter change does not invalidate it (that is the standing rule in
    CLAUDE.md §2.3). The first run of `scripts/sweep_tools.py` against a
    deliberately broken formatter therefore reported the OLD, correct values
    and passed: every call logged `cache_hit`.

    A detector that reads its own cache is not driving anything. Set
    MOSAIC_BYPASS_CACHE=1 for any process whose job is to observe what the
    code currently produces.
    """
    return os.environ.get("MOSAIC_BYPASS_CACHE", "") == "1"


def tool_cache_get(tool_name: str, params: dict[str, Any]) -> str | None:
    if _bypass() or tool_name in NON_CACHEABLE:
        return None
    key = _key(tool_name, normalize_params(params), _kg_version())
    hit = _get("tool_response_cache", key)
    if hit is not None:
        logger.info("cache_hit tool=%s", tool_name)
        return hit if isinstance(hit, str) else json.dumps(hit)
    logger.info("cache_miss tool=%s", tool_name)
    return None


def tool_cache_put(tool_name: str, params: dict[str, Any], response: str) -> None:
    # Bypass on WRITE too: a sweep must not populate the cache other callers
    # then read, and a bypassed process has no business warming it.
    if _bypass() or tool_name in NON_CACHEABLE:
        return
    ttl = _TTL_BY_TOOL.get(tool_name, _DEFAULT_TTL)
    v = _kg_version()
    key = _key(tool_name, normalize_params(params), v)
    try:
        _db().execute(
            """
            INSERT INTO tool_response_cache
                (cache_key, tool_name, kg_version, response, expires_at)
            VALUES (%s, %s, %s, %s::jsonb, NOW() + (%s || ' seconds')::interval)
            ON CONFLICT (cache_key) DO UPDATE
                SET response = EXCLUDED.response,
                    expires_at = EXCLUDED.expires_at
            """,
            (key, tool_name, v, json.dumps(response), str(ttl)),
        )
    except Exception as e:
        logger.debug("cache put skipped (tool=%s): %s", tool_name, e)


# --- agent-response cache -------------------------------------------------

def agent_cache_get(query: str, agent_version: str) -> str | None:
    key = _key(query.strip().lower(), agent_version, _kg_version())
    hit = _get("agent_response_cache", key)
    if hit is not None:
        logger.info("cache_hit agent v=%s", agent_version)
        return hit if isinstance(hit, str) else json.dumps(hit)
    logger.info("cache_miss agent v=%s", agent_version)
    return None


def agent_cache_put(query: str, agent_version: str, response: str) -> None:
    v = _kg_version()
    key = _key(query.strip().lower(), agent_version, v)
    try:
        _db().execute(
            """
            INSERT INTO agent_response_cache
                (cache_key, kg_version, response, expires_at)
            VALUES (%s, %s, %s::jsonb, NOW() + (%s || ' seconds')::interval)
            ON CONFLICT (cache_key) DO UPDATE
                SET response = EXCLUDED.response,
                    expires_at = EXCLUDED.expires_at
            """,
            (key, v, json.dumps(response), str(_AGENT_TTL)),
        )
    except Exception as e:
        logger.debug("agent cache put skipped: %s", e)


class CachePurgeUnavailable(Exception):
    """No cache table could be reached. Distinct from 'nothing to purge'."""


def purge_expired() -> int:
    """Delete expired rows from both caches. Returns rows removed.

    ⚠️ RAISES if NO table could be reached, and that is the whole point.

    This used to catch every exception at `logger.debug` and return 0, so an
    unreachable database was indistinguishable from an empty one. Measured on
    the live nightly cron (run 29725406819, 2026-07-20): `DATABASE_URL:` was
    EMPTY, nothing connected, and the job printed **"Purged 0 expired cache
    row(s)"** and went green — every night, for as long as the secret has been
    missing. "0 purged" reads exactly like "nothing needed purging", which is
    why nobody saw it.

    A missing table is still tolerated: `agent_response_cache` genuinely may
    not exist on an older deployment, and that is a real condition rather than
    a fault. But if BOTH fail, the database is unreachable and the caller must
    hear about it.
    """
    n = 0
    reached = 0
    failures: list[str] = []
    for tbl in ("tool_response_cache", "agent_response_cache"):
        try:
            rows = _db().execute(
                f"DELETE FROM {tbl} WHERE expires_at <= NOW() RETURNING 1"  # noqa: S608
            )
            n += len(rows)
            reached += 1
        except Exception as e:  # noqa: BLE001 — re-raised below if total
            failures.append(f"{tbl}: {type(e).__name__}: {str(e).splitlines()[0][:120]}")
            logger.warning("purge failed for %s: %s", tbl, e)
    if reached == 0:
        raise CachePurgeUnavailable(
            "no cache table could be purged — the database was not reachable. "
            + " | ".join(failures)
        )
    return n
